name = "Tencent Open House #10"

  [[party]]
  name = "Pasta.dart.kt.js.swift"
  url = "https://www.facebook.com/photo.php?fbid=10210135782905247&set=a.1302432655084&type=3&permPage=1"
  place = "Pasta & Noodle Bar"

