name = "Angular Meetup NOV 2018"

  [[party]]
  name = "ng-beer-pizza.ts"
  url = "https://www.facebook.com/photo.php?fbid=10205312191920594&set=a.1615299358663&type=1&theater"
  place = "7 Peaks Software Office"

