name = "DevOps BKK 2018"

  [[party]]
  name = "Future of software community in Thailand?"
  url = "https://www.facebook.com/oddsteam/videos/528151600962749/"
  live = "https://www.facebook.com/oddsteam/videos/528151600962749/"
  place = "AINU Hokkaido Izakaya & Bar"

