name = "BKK.js #4 Puppeteer Edition"

  [[party]]
  name = "Bingsu.js (without Bingsu)"
  url = "https://www.facebook.com/photo.php?fbid=10210792889852510&set=a.1302432655084&type=3&permPage=1"
  place = "Hollys Coffee The Street"

