name = "The Stupid Hackathon Thailand #2"

  [[party]]
  name = "Domino.js"
  url = "https://www.facebook.com/photo.php?fbid=10210377558149477&set=a.10210374198345484&type=3&permPage=1"
  place = "Domino Pizza I'm Park"

