name = "Angular Meetup OCT 2018"

  [[party]]
  name = "ng new mango-bingsu-toast --minimal"
  url = "https://www.facebook.com/photo.php?fbid=10205213059722351&set=a.1615299358663&type=3&theater"
  place = "Hollys Coffee Siamkit"

