name = "Vue.js Thailand #4"

  [[party]]
  name = "Ramen.vue"
  url = "https://www.facebook.com/photo.php?fbid=10210792898012714&set=a.1302432655084&type=3&permPage=1"
  place = "Tonkotsu Kazan Ramen The Street"

