name = "GDG DevFest 2018"

  [[party]]
  name = "bbq-plaza.wasm"
  url = "https://web.facebook.com/photo.php?fbid=10212954269917996&set=a.1095604516845&type=3&permPage=1"
  place = "Siam Square One"

