name = "Facebook DevC Bangkok Meetup: Becoming a Successful Software Engineer"

  [[party]]
  name = "frenchFried.js"
  url = "https://www.facebook.com/photo.php?fbid=10158033540010558&set=a.10150764155390558&type=3&permPage=1"
  place = "HOBS at centralwOrld"
