name = "DevOps Bangkok"

  [[party]]
  name = "NotBingsu.js"
  url = "https://web.facebook.com/photo.php?fbid=10210909195400076&set=a.1302432655084&type=3&__xts__%5B0%5D=68.ARDHby1Sr8ZnqOk_ZnPPucdd2uM2x-_aAzHIQGkFhsTBT-E6Ts0_WvVz06IlhzfetC9cH270LYHLiUuoqqLdG6sjXuqgYonTxS-zVD38bWGDkJPr3jvPBl3Tj7bzPJTV9_3CYl8PcYpTeWioiNj49_CdtZdZwnmT05kBi2hyksN14wGRB1SOY42P9yYsvFOYtoouXR74lKlTKAMEZ7Xkl5Pzm8dOfA&__tn__=-R"
  place = "ZaabOne Ratchada"

