name = "Software Architect Meetup Bangkok #1"

  [[party]]
  name = "Bingsu.js"
  url = "https://www.facebook.com/photo.php?fbid=10210332899793046&set=a.1302432655084&type=3&permPage=1"
  place = "Hollys Coffee The Street"

