name = "Next Stack: Entrepreneur edition"

  [[party]]
  name = "bingsu.co.th"
  url = "https://www.facebook.com/photo.php?fbid=10213242836291975&set=a.1095604516845&type=3&theater"
  place = "Hollys Coffee The Street"

