name = "BKK.js #3"

  [[party]]
  name = "Pre-Bingsu.js Texas.js"
  url = "https://www.facebook.com/photo.php?fbid=10210244751869403&set=a.1302432655084&type=3&permPage=1"
  place = "Texas Chicken Siamkit"

  [[party]]
  name = "Post-Texas.js Bingsu.js"
  url = "https://www.facebook.com/photo.php?fbid=10210244941394141&set=a.1302432655084&type=3&permPage=1"
  place = "Hollys Coffee Siamkit"

