name = "TypeScript Thailand Meetup #1"

  [[party]]
  name = "TookLaeDee.ts"
  url = "https://www.facebook.com/photo.php?fbid=10210568039511392&set=a.1302432655084&type=3&permPage=1"
  place = "Took Lae Dee The Street"

