name = "LOVE CODE MEETUP #นัดโค้ด by Women Who Code"

  [[party]]
  name = "DonChickenAndSulbing.js"
  url = "https://www.facebook.com/photo.php?fbid=10211670828600430&set=a.1302432655084&type=3"
  place = "Don Chicken K Town"
