name = "BKK.js #6 - Web Components Special Edition"

  [[party]]
  name = "<plearnwan-panich></plearnwan-panich>"
  url = "https://web.facebook.com/photo.php?fbid=10211741247720864&set=a.1302432655084&type=3"
  place = "Plearnwan Panich The Street"

  [[party]]
  name = "<bingsu-js></bingsu-js>"
  url = "https://web.facebook.com/photo.php?fbid=10211741255561060&set=a.1302432655084&type=3"
  place = "Hollys Coffee The Street"
