name = "Code in the Dark Thailand #3: CNX 2019"

  [[party]]
  name = "หม่าล่า.css"
  url = "https://www.facebook.com/photo.php?fbid=10211683292552021&set=a.1302432655084&type=3"
  place = "Funky Grill"
